allowBuilds:
  '@owservable/core': true
  '@owservable/folders': true
  better-sqlite3: true
  es5-ext: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@owservable/core'
  - '@owservable/folders'
